spring:
  application:
    name: "configserver"
  profiles:
    active: git
  cloud:
    config:
      server:
        git:
          uri: https://github.com/issam-atl/Microservice-Issam.git
          default-label: main
          clone-on-start: true
          search-paths: config-repo
management:
  endpoints:
    web:
      exposure:
        include: '*'

server:
  port: 9999